export const REGISTER_CAMPAIGN_FAIL="REGISTER_CAMPAIGN_FAIL";
export const REGISTER_CAMPAIGN_SUCCESS="REGISTER_CAMPAIGN_SUCCESS";
export const REGISTER_CAMPAIGN_REQUEST="REGISTER_CAMPAIGN_REQUEST";

export const UPDATE_CAMPAIGN_FAIL="UPDATE_CAMPAIGN_FAIL";
export const UPDATE_CAMPAIGN_SUCCESS="UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_REQUEST="UPDATE_CAMPAIGN_REQUEST";

export const DELETE_CAMPAIGN_FAIL="DELETE_CAMPAIGN_FAIL";
export const DELETE_CAMPAIGN_SUCCESS="DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_REQUEST="DELETE_CAMPAIGN_REQUEST";

export const VIEW_CAMPAIGN_FAIL="VIEW_CAMPAIGN_FAIL";
export const VIEW_CAMPAIGN_SUCCESS="VIEW_CAMPAIGN_SUCCESS";
export const VIEW_CAMPAIGN_REQUEST="VIEW_CAMPAIGN_REQUEST";

export const SINGLE_CAMPAIGN_FAIL="SINGLE_CAMPAIGN_FAIL";
export const SINGLE_CAMPAIGN_SUCCESS="SINGLE_CAMPAIGN_SUCCESS";
export const SINGLE_CAMPAIGN_REQUEST="SINGLE_CAMPAIGN_REQUEST";

export const SEND_CAMPAIGN_REQUEST ="SEND_CAMPAIGN_REQUEST";

export const SEND_CAMPAIGN_SUCCESS ="SEND_CAMPAIGN_SUCCESS";

export const SEND_CAMPAIGN_FAIL ="SEND_CAMPAIGN_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";