export const ADD_COMMENT_REGISTER = "ADD_COMMENT_REGISTER";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const VIEW_COMMENT_REGISTER = "VIEW_COMMENT_REGISTER";
export const VIEW_COMMENT_SUCCESS = "VIEW_COMMENT_SUCCESS";
export const VIEW_COMMENT_FAIL = "VIEW_COMMENT_FAIL";

export const REPLY_COMMENT_REGISTER = "REPLY_COMMENT_REQUEST";
export const REPLY_COMMENT_SUCCESS = "REPLY_COMMENT_SUCCESS";
export const REPLY_COMMENT_FAIL = "REPLY_COMMENT_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";